// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=MineColonies_Tweaks
maven_group=steve_gall.minecolonies_tweaks
mod_id=minecolonies_tweaks
mod_version=3.21
mod_name=Tweaks addon for MineColonies
mod_description=Tweak your minecolonies experience. Custom Tools for citizen, more configuration etc...
mod_license=GPL 3.0
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-tweaks
mod_source=https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks
mod_issues=https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.200
neoforge_api_version_range=[21.1.194,)

// Required
minecolonies_version=1.1.1241-1.21.1-snapshot
structurize_version=1.0.799-1.21.1-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
blockui_version=1.0.199-1.21.1-snapshot
domumornamentum_version=1.0.223-snapshot
domumornamentum_file=7231908

// Optional
jei_version=19.19.6.235
curios_file=6529130

// Runtime Only
jade_file=5729884
mekanism_version=10.7.15.81
configured_file=5873783
